Hide `Throwable` trampoline extension functions from Objective-C
For Objective-C export, they are considered conflicts with the member methods
for which they are trampolines.

```
error: name is mangled when generating Objective-C header because it conflicts with fun fillInStackTrace(): Throwable defined in java.lang.Throwable
    (at fun Throwable.fillInStackTrace(): Throwable defined in javaemul.lang)
error: name is mangled when generating Objective-C header because it conflicts with fun initCause(cause: Throwable?): Throwable defined in java.lang.Throwable
    (at fun Throwable.initCause(cause: Throwable?): Throwable defined in javaemul.lang)
…
```
PiperOrigin-RevId: 772809911