Add Kotlin’s version of `addAll` to `Collection` etc.
Transpiled Java always uses `java_addAll` instead. But the transpiler needs to
be aware of the method so it can determine whether to override it in case a
class inherits multiple implementations of the method.

Only `addAll` for now because that was the only method we’ve already run into
with real code:

```
com/google/common/collect/ImmutableList.kt:48:10: error: class ’ImmutableList’ must override public open fun addAll(c: Collection<E>): Boolean defined in javaemul.lang.JavaList because it inherits many implementations of it
abstract class ImmutableList<E: Any>: JavaList<E>, RandomAccess, ImmutableCollection<E> {
         ^
```

PiperOrigin-RevId: 489472999