Resolve ObjC export mangling “conflict”
```
error: name is mangled when generating Objective-C header because it conflicts with fun <V> MutableCollection<V>.java_remove(value: Any?): Boolean defined in javaemul.lang
    (at fun <K, V> MutableMap<K, V>.java_remove(key: Any?): V? defined in javaemul.lang)
```
PiperOrigin-RevId: 772811665